### ISSUE TITLE
Better avatar placeholder

### ISSUE THREAD

**Issue by antfu** [breadsplit/breadsplit#38]
Should we design a pattern ourselves or just use other placeholder services? This functions should works **Offline**.

Current using: https://avatars.dicebear.com/
Options:
- http://avatars.adorable.io/

## Example
![image](https://user-images.githubusercontent.com/11247099/57115945-8e2dfd00-6d84-11e9-96b6-116382fe3af5.png)

## Reference
https://medium.com/@morgoe876/placeholder-avatars-dfb02b9b7af5

**Comment by FlorianKoerner** [comment]
DiceBear Avatars also works offline. 😃 
https://www.npmjs.com/package/@dicebear/avatars
