### ISSUE TITLE
"No content" placeholders

### ISSUE THREAD

**Issue by antfu** [breadsplit/breadsplit#84]
Some thing like this, we may need for:
- [ ] Groups
- [ ] Transactions
- [ ] Settle up (all settled)

![image](https://user-images.githubusercontent.com/11247099/58170010-e5105d80-7cc4-11e9-85f1-56304ae9a63f.png)

**Comment by Kevinwuu** [comment]
nice examples:
https://www.pinterest.com/luduan8811/empty-page/
