### ISSUE TITLE
Unread activities indicator

### ISSUE THREAD

**Issue by antfu** [breadsplit/breadsplit#89]
![image](https://user-images.githubusercontent.com/11247099/58440215-1f398f00-810b-11e9-85d4-5bd2344ca295.png)

Also, an option for user to turn off this feature would be nice.

**Comment by antfu** [comment]
```ts
  this.$store.getters['group/unreadsOf'](id)

  this.$store.commit('group/clearUnreads')
```

**Comment by antfu** [comment]
@raymondchiang 進展如何?

**Comment by raymondchiang** [comment]
晚上孩子會生出來

**Comment by antfu** [comment]
祝順產🤡

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
