### ISSUE TITLE
Number changing animation

### ISSUE THREAD

**Issue by antfu** [breadsplit/breadsplit#96]
https://inorganik.github.io/countUp.js/
https://github.hubspot.com/odometer/docs/welcome/

**Comment by Hasan-Ali** [comment]
I'm new around here, just to be sure, you want the animations from the 1st link to be used with the project in the 2nd link,,, did i get this right?

**Comment by antfu** [comment]
Hi @Hasan-Ali these two link are just possible approach reference. It can be one or them or completely different solution.
