### ISSUE TITLE
Sponsor Button

### ISSUE THREAD

**Issue by antfu** [breadsplit/breadsplit#98]
https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository
![image](https://user-images.githubusercontent.com/11247099/58795519-78368500-862d-11e9-8149-605b3f63cc5f.png)

**Comment by antfu** [comment]
It's very simple, anyone want to try this? @raymondchiang @waynelens @Kevinwuu @zychang39

**Comment by dmaynard51** [comment]
May I try this?
